object frmSobre: TfrmSobre
  Left = 0
  Top = 0
  BorderStyle = bsToolWindow
  Caption = 'Sobre'
  ClientHeight = 272
  ClientWidth = 428
  Color = 16312022
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Visible = True
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 13
end
